---
- hosts: localhost
  become: true
  connection: local
  vars:
  roles:
  tasks:
    - name: setting Debian facts
      set_fact:
        apache2_log_dir: "/var/log/apache2"
        apache2_web_group: "www-data"
        apache2_web_owner: "www-data"
        apache2_web_root: "/var/www/html"
      when: ansible_os_family == "Debian"

    - name: Generating Wordpress Salt
      command: "curl https://api.wordpress.org/secret-key/1.1/salt/"
      register: "wordpress_salt"

    - name: Configuring Wordpress
      template:
        src: "/wp-config.php.j2"
        dest: "{{ wordpress_root_dir }}/wordpress/wp-config.php"

    - name: Configuring Wordpress Permissions
      file:
        path: "{{ wordpress_root_dir }}"
        state: "directory"
        owner: "{{ apache2_web_owner }}"
        group: "{{ apache2_web_group }}"
        recurse: yes

    - name: Configuring Wordpress Apache2 Default Site
      template:
        src: "/000-default.conf.j2"
        dest: "/etc/apache2/sites-available/000-default.conf"
