---
- hosts: localhost
  become: true
  connection: local
  vars:
    wordpress_dl_file: 'wordpress-{{ wordpress_ver }}.tar.gz'
    wordpress_dl_uri: 'https://wordpress.org'
    wordpress_dl: '{{ wordpress_dl_uri }}/{{ wordpress_dl_file }}'
  roles:
  tasks:
    - name: setting Debian facts
      set_fact:
        apache2_log_dir: "/var/log/apache2"
        apache2_web_group: "www-data"
        apache2_web_owner: "www-data"
        apache2_web_root: "/var/www/html"
      when: ansible_os_family == "Debian"

    - name: setting PHP version
      set_fact:
        php_path: 'etc/php5'  #no leading / for template path
        php_ver: 5
      when: >
            ansible_distribution == "Debian" or
            (ansible_distribution == "Ubuntu" and
            ansible_distribution_version <= '14.04')

    - name: setting PHP version
      set_fact:
        php_path: 'etc/php/7.0'  #no leading / for template path
        php_ver: 7.0
      when: >
            (ansible_distribution == "Ubuntu" and
            ansible_distribution_version >= '16.04')

    - name: Update Apt-Cache
      apt:
        update_cache: yes

    - name: Installing Pre-Reqs
      apt:
        name: "{{ item }}"
        state: "present"
        install_recommends: no
      with_items:
        - 'curl'
        - 'php{{ php_ver }}-mysql'
        - 'php{{ php_ver }}-cli'
        - 'php{{ php_ver }}-cgi'
        - 'php{{ php_ver }}-gd'

    - name: Downloading Wordpress {{ wordpress_ver }}
      get_url:
        url: "{{ wordpress_dl }}"
        dest: "{{ wordpress_root_dir }}/{{ wordpress_dl_file }}"

    - name: Extracting Wordpress {{ wordpress_ver }}
      unarchive:
        src: "{{ wordpress_root_dir }}/{{ wordpress_dl_file }}"
        dest: "{{ wordpress_root_dir }}/"
